# dein.toml

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'takkii/Bignyanco'

[[plugins]]
repo = 'takkii/ruby-dictionary3'

[[plugins]]
repo = 'takkii/totolot'

[[plugins]]
repo = 'takkii/Jet-black-wings'
build = 'ruby install.rb'

[[plugins]]
repo = 'takkii/MinTab'

[[plugins]]
repo = 'takkii/vim-com'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'ncm2/float-preview.nvim.git'

#[[plugins]]
#repo = 'fatih/vim-go'
#hook_add = '''
#  let g:go_fmt_command = "goimports"
#  let g:go_def_mapping_enabled = 0
#  let g:go_doc_keywordprg_enabled = 0
#'''

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'
