# dein_lazy.toml

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = ['InsertEnter']
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/deoppet.nvim'
hook_source = '''
  call deoppet#initialize()
  call deoppet#custom#option('snippets_dirs',
  \ globpath(&runtimepath, 'neosnippets', 1, 1))

  imap <C-k>  <Plug>(deoppet_expand)
  imap <C-f>  <Plug>(deoppet_jump_forward)
  imap <C-b>  <Plug>(deoppet_jump_backward)
  smap <C-f>  <Plug>(deoppet_jump_forward)
  smap <C-b>  <Plug>(deoppet_jump_backward)
'''
on_i  = 1
on_ft = ['snippet']

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = 'C:/Users/sudok/go/bin/gocode.exe'
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = 'powershell.exe .\install.ps1'
on_ft = 'ruby,go,perl,python'
on_event = ['InsertEnter']
depends = ['deoplete.nvim']
